### PR TITLE
HT-3232: Add compression and static cache headers

### PR DESCRIPTION
**Pull request by aelkiss**
This should expand to the requested:

AddOutputFilterByType DEFLATE text/html text/plain text/xml text/css application/javascript application/xml application/xhtml+xml application/json image/svg+xml

ExpiresActive On
ExpiresDefault "modification plus 2 hours"

### CODE REVIEW

**Comment by aelkiss** [comment]
FYI @respinos - for some reason I can't add you as a reviewer

**Comment by aelkiss** [comment]
I'll get this going on `test.babel.hathitrust.org`

**Comment by aelkiss** [comment]
@respinos  says: "this is looking good — so far the expected resources are getting Expires headers."

**Comment by aelkiss** [comment]
@rrotter  Let's plan on merging this next week.

**Review by rrotter — APPROVED** [review]

**Pull request merged**
