### PR TITLE
HT-2523, HT-2749, HT-2433: Add dependencies for additional backup locations

### PR DESCRIPTION
**Pull request by aelkiss**

### CODE REVIEW

**Comment by aelkiss** [comment]
Just adds one package for HT machines.

FWIW, I think we are probably close to being able to migrate ingest to k8s, but I don't want to take that on quite yet or for that to block getting up and running with this.

**Comment by aelkiss** [comment]
@daaang  Any concern with merging this? Just adds one package.

**Comment by aelkiss** [comment]
We never merged the HT-2433 branch; I cherry-picked that commit here and hopefully we can just get that merged soon?

**Review by rrotter — APPROVED** [review]
I don't have any concerns about this.

**Pull request merged**
