### PR TITLE
Delete unused manifests

### PR DESCRIPTION
**Pull request by rrotter**
* purged checks for jessie
* Compared list of manifests in use from puppet-query to list of all manifests from grepping nebula.
* One major category of unused manifests per commit.
* Removed manifests, so far:
```
nebula::profile::apt_mirror
nebula::profile::base::environment
nebula::profile::hathitrust::clamav
nebula::profile::hathitrust::solr_lss
nebula::role::apt_mirror
nebula::role::hathitrust::backup
nebula::role::hathitrust::dev::app_host
nebula::role::hathitrust::solr::lss_aws
nebula::role::hathitrust::vmhost
nebula::role::jira::prod
nebula::role::unison
nebula::role::webhost::hathitrust
```
* Remaining unused manifests listed below:
```
nebula::profile::apache::cosign
nebula::profile::apt::buster
nebula::profile::docker_registry
nebula::profile::elastic::filebeat::prospectors::apache
nebula::profile::elastic::filebeat::prospectors::syslog
nebula::profile::moku
nebula::profile::named_instances::docker
nebula::role::app_host::dev_private
nebula::role::app_host::docker
nebula::role::app_host::hyrax
nebula::role::app_host::prod_private
nebula::role::archivematica
nebula::role::deploy_host
nebula::role::docker_registry
nebula::role::fulcrum
nebula::role::log_host
nebula::role::puppet::master_without_db
nebula::role::textassembler
nebula::role::webhost::quod
nebula::role::webhost::www_lib
nebula::role::webhost::www_lib_deepblue
```

### CODE REVIEW

**Comment by rrotter** [comment]
I'm done. Anything else can go in another PR.

**Comment by aelkiss** [comment]
I am not expecting to re-use any of those deleted manifests. @rrotter and I looked at the solr manifests recently and I believe there is very little of value there currently.

**Comment by rrotter** [comment]
I'm fairly confident that none of the files that I deleted are referenced elsewhere. I also cleaned out any fixtures and templates I found that were only used by the deleted code.

Because it's dead code, nothing here should do anything on a running server. I just pushed an update that reverted the only line changed that would have: an if statement affecting vm creation in manifests/virtual_machine.pp.

**Comment by skorner** [comment]
Sounds good all around!

**Comment by rrotter** [comment]
rebased, switched to larger ci runner. ran in 6 minutes!

**Pull request merged**
